version: '3.7'
services:
  frontend:
    image: frontend
    build: ./frontend
    depends_on:
      - backend
    environment:
      BACKEND_URL: ${BACKEND_URL}
  backend:
    image: backend
    build: ./backend
    environment:
      TEST_DATABASE_URI: ${TEST_DATABASE_URI}
      DATABASE_URI: ${DATABASE_URI}
      SECRET_KEY: ${SECRET_KEY}
      BACKEND_URL: ${BACKEND_URL}
    depends_on:
      - mysql
  mysql:
    image: mysql
    build: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  nginx:
    image: nginx
    ports:
      - target: 80
        published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
