version: '3.3'
services:
  frontend:
    image: jstoneqa/sfia-3-frontend:dc
    build: ./frontend
    ports:
    - target: 3000
      published: 3000
      protocol: tcp
    stdin_open: true
    tty: true
    depends_on:
      - backend
  backend:
    image: jstoneqa/sfia-3-backend:dc
    build: ./backend 
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    stdin_open: true
    tty: true
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on: 
      - frontend
      - backend
